services:
  mongo1:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--keyFile", "/data/configdb/keyfile"]
    ports:
      - 27017:27017
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
      - "./mongo-keyfile:/data/configdb/keyfile"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

  mongo2:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27018", "--keyFile", "/data/configdb/keyfile"]
    ports:
      - 27018:27018
    volumes:
      - "mongo2_data:/data/db"
      - "mongo2_config:/data/configdb"
      - "./mongo-keyfile:/data/configdb/keyfile"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

  mongo3:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27019", "--keyFile", "/data/configdb/keyfile"]
    ports:
      - 27019:27019
    volumes:
      - "mongo3_data:/data/db"
      - "mongo3_config:/data/configdb"
      - "./mongo-keyfile:/data/configdb/keyfile"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret


  web:
    build: 
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      MONGO_CONNECTION_STRING: "mongodb://admin:secret@mongo1:27017,mongo2:27018,mongo3:27019/?replicaSet=rs0"
    depends_on:
      - mongo1
      - mongo2
      - mongo3
   
    

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo1_config:
  mongo2_config:
  mongo3_config: